pipeline {
    agent any
    stages {
        stage('CheckOut') {
            steps {
                git url: "https://github.com/Mallikarjunakadi/my-deployment.git", branch: "main"
                sh 'echo Passed'
            }
        }

        stage('Build and Push Docker Image') {
            environment {
                DOCKER_IMAGE = "mallikarjunkadi11/hello-world-app:${BUILD_NUMBER}"
                // DOCKERFILE_LOCATION = "java-maven-sonar-argocd-helm-k8s/spring-boot-app/Dockerfile"
                REGISTRY_CREDENTIALS = credentials('dockerHub')
            }
            steps {
                script {
                    sh 'cd my-python-app && docker build -t ${DOCKER_IMAGE} .'
                    def dockerImage = docker.image("${DOCKER_IMAGE}")
                    docker.withRegistry('https://index.docker.io/v1/', "dockerHub") {
                        dockerImage.push()
                    }
                }
            }
        }
    }
}
