pipeline
{
    agent any
stages
{
  stage('CheckOut')
  {
    steps
    {
         git url: "https://github.com/Mallikarjunakadi/my-deployment.git", branch: "main"
         sh 'echo Passed'
    }
  }
  
   stage("Build & Test"){
            steps{
                sh "docker build . -t hello-world-app"
            }
        }

  stage("Push to DockerHub"){
            steps{
                withCredentials([usernamePassword(credentialsId:"dockerHub",passwordVariable:"dockerHubPass",usernameVariable:"dockerHubUser")]){
                    sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPass}"
                    sh "docker tag hello-world-app ${env.dockerHubUser}/hello-world-app:latest"
                    sh "docker push ${env.dockerHubUser}/hello-world-app:latest" 
                }
            }
        }
}
}