apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-hello-world-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app 
  template:
    metadata:
      labels:
        app: hello-world-app 
    spec:
      containers:
      - name: python-hello-world-container
        image: champ4356/hello-world-app:26  # 22 Replace with your Docker image name
        ports:
        - containerPort: 8000  # Port your application listens on inside the container
